import type { KpiDefinition, ThresholdBand } from "@/domain/types";

/**
 * Product decision: thresholds are CEO-oriented defaults for a R$100M cleaning/paper distributor.
 * Adjust per tenant in Config; formulas stay central here.
 */
export const KPI_CATALOG: readonly KpiDefinition[] = [
  {
    id: "revenue_day",
    name: "Faturamento do dia",
    description: "Soma das vendas faturadas no dia (NFs emitidas).",
    formula: "SUM(invoice.net_amount) WHERE invoice_date = as_of_date",
    unit: "BRL",
    horizon: "daily",
    owner: "commercial",
    higherIsBetter: true,
    thresholds: { green: 1, yellow: 0.9 },
    source: "sales.invoices",
    playbook: [
      "Comparar vs meta diária e vs mesmo dia da semana anterior",
      "Checar backlog de pedidos não faturados",
      "Priorizar contas nacionais com pedidos liberados",
    ],
  },
  {
    id: "fill_rate_day",
    name: "Fill rate",
    description: "% de linhas atendidas integralmente no pedido.",
    formula: "fulfilled_lines / requested_lines",
    unit: "percent",
    horizon: "daily",
    owner: "operations",
    higherIsBetter: true,
    thresholds: { green: 0.95, yellow: 0.9 },
    source: "sales.orders + stock",
    playbook: [
      "Listar SKUs A em ruptura",
      "Replanejar compras emergenciais",
      "Oferecer substituto homologado ao cliente",
    ],
  },
  {
    id: "otif_day",
    name: "OTIF",
    description: "% de pedidos entregues no prazo e completos.",
    formula: "orders_on_time_in_full / orders_due",
    unit: "percent",
    horizon: "daily",
    owner: "operations",
    higherIsBetter: true,
    thresholds: { green: 0.92, yellow: 0.85 },
    source: "logistics.deliveries",
  },
  {
    id: "cash_in_day",
    name: "Caixa recebido no dia",
    description: "Baixas de recebíveis no dia.",
    formula: "SUM(payments.amount) WHERE payment_date = as_of_date",
    unit: "BRL",
    horizon: "daily",
    owner: "finance",
    higherIsBetter: true,
    thresholds: { green: 1, yellow: 0.85 },
    source: "finance.payments",
  },
  {
    id: "overdue_ar",
    name: "Recebíveis vencidos",
    description: "Saldo em aberto com vencimento < hoje.",
    formula: "SUM(receivables.open_amount) WHERE due_date < today AND status = open",
    unit: "BRL",
    horizon: "daily",
    owner: "finance",
    higherIsBetter: false,
    thresholds: { green: 2_000_000, yellow: 4_000_000 },
    source: "finance.receivables",
    playbook: [
      "Cobrar top 10 inadimplentes por valor",
      "Bloquear novos pedidos se política de crédito exigir",
      "Negociar acordo com desconto financeiro se ROI positivo",
    ],
  },
  {
    id: "stockout_sku_a",
    name: "Rupturas SKU A",
    description: "Quantidade de SKUs classe A com estoque zero ou abaixo do mínimo.",
    formula: "COUNT(sku WHERE abc='A' AND on_hand < min_stock)",
    unit: "count",
    horizon: "daily",
    owner: "operations",
    higherIsBetter: false,
    thresholds: { green: 3, yellow: 8 },
    source: "inventory.snapshots",
  },
  {
    id: "returns_day",
    name: "Devoluções do dia",
    description: "Valor de devoluções/credit notes no dia.",
    formula: "SUM(returns.net_amount) WHERE return_date = as_of_date",
    unit: "BRL",
    horizon: "daily",
    owner: "operations",
    higherIsBetter: false,
    thresholds: { green: 50_000, yellow: 120_000 },
    source: "sales.returns",
  },
  {
    id: "revenue_week",
    name: "Faturamento da semana",
    description: "Receita líquida da semana corrente.",
    formula: "SUM(invoice.net_amount) WHERE week = current_week",
    unit: "BRL",
    horizon: "weekly",
    owner: "commercial",
    higherIsBetter: true,
    thresholds: { green: 1, yellow: 0.92 },
    source: "sales.invoices",
  },
  {
    id: "gross_margin_week",
    name: "Margem bruta semanal",
    description: "(Receita - CMV) / Receita.",
    formula: "(revenue - cogs) / revenue",
    unit: "percent",
    horizon: "weekly",
    owner: "ceo",
    higherIsBetter: true,
    thresholds: { green: 0.28, yellow: 0.24 },
    source: "sales.invoices + product.cost",
  },
  {
    id: "freight_pct_week",
    name: "Frete % receita",
    description: "Custo de frete / receita da semana.",
    formula: "freight_cost / revenue",
    unit: "percent",
    horizon: "weekly",
    owner: "operations",
    higherIsBetter: false,
    thresholds: { green: 0.045, yellow: 0.06 },
    source: "logistics.freight_costs",
  },
  {
    id: "ar_aging_60",
    name: "Aging > 60 dias",
    description: "Recebíveis abertos com atraso acima de 60 dias.",
    formula: "SUM(open_amount) WHERE days_overdue > 60",
    unit: "BRL",
    horizon: "weekly",
    owner: "finance",
    higherIsBetter: false,
    thresholds: { green: 1_500_000, yellow: 3_000_000 },
    source: "finance.receivables",
  },
  {
    id: "revenue_month",
    name: "Receita do mês",
    description: "Faturamento líquido do mês.",
    formula: "SUM(invoice.net_amount) WHERE month = current_month",
    unit: "BRL",
    horizon: "monthly",
    owner: "commercial",
    higherIsBetter: true,
    thresholds: { green: 1, yellow: 0.95 },
    source: "sales.invoices",
  },
  {
    id: "gross_margin_month",
    name: "Margem bruta mensal",
    description: "(Receita - CMV) / Receita no mês.",
    formula: "(revenue - cogs) / revenue",
    unit: "percent",
    horizon: "monthly",
    owner: "ceo",
    higherIsBetter: true,
    thresholds: { green: 0.28, yellow: 0.24 },
    source: "sales.invoices + product.cost",
  },
  {
    id: "dso",
    name: "DSO",
    description: "Days Sales Outstanding.",
    formula: "(AR / revenue_last_30d) * 30",
    unit: "days",
    horizon: "monthly",
    owner: "finance",
    higherIsBetter: false,
    thresholds: { green: 35, yellow: 45 },
    source: "finance.receivables + sales",
  },
  {
    id: "dio",
    name: "DIO",
    description: "Days Inventory Outstanding.",
    formula: "(inventory_value / cogs_last_30d) * 30",
    unit: "days",
    horizon: "monthly",
    owner: "operations",
    higherIsBetter: false,
    thresholds: { green: 45, yellow: 60 },
    source: "inventory + cogs",
  },
  {
    id: "dpo",
    name: "DPO",
    description: "Days Payable Outstanding.",
    formula: "(AP / cogs_last_30d) * 30",
    unit: "days",
    horizon: "monthly",
    owner: "finance",
    higherIsBetter: true,
    thresholds: { green: 30, yellow: 20 },
    source: "finance.payables",
  },
  {
    id: "cash_conversion_cycle",
    name: "Ciclo de caixa",
    description: "DSO + DIO - DPO.",
    formula: "dso + dio - dpo",
    unit: "days",
    horizon: "monthly",
    owner: "ceo",
    higherIsBetter: false,
    thresholds: { green: 50, yellow: 70 },
    source: "derived",
  },
  {
    id: "top10_concentration",
    name: "Concentração top 10 clientes",
    description: "% da receita nos 10 maiores clientes (mês).",
    formula: "revenue_top10 / revenue_month",
    unit: "percent",
    horizon: "monthly",
    owner: "ceo",
    higherIsBetter: false,
    thresholds: { green: 0.35, yellow: 0.45 },
    source: "sales.invoices",
    playbook: [
      "Mapear risco de churn por conta nacional",
      "Acelerar hunter em contas mid-market",
      "Revisar condições comerciais dos top 3",
    ],
  },
  {
    id: "revenue_quarter",
    name: "Receita do trimestre",
    description: "Faturamento líquido do trimestre.",
    formula: "SUM(invoice.net_amount) WHERE quarter = current_quarter",
    unit: "BRL",
    horizon: "quarterly",
    owner: "ceo",
    higherIsBetter: true,
    thresholds: { green: 1, yellow: 0.95 },
    source: "sales.invoices",
  },
  {
    id: "ebitda_proxy_quarter",
    name: "EBITDA (proxy)",
    description: "Receita - CMV - opex operacional (proxy gerencial).",
    formula: "revenue - cogs - opex",
    unit: "BRL",
    horizon: "quarterly",
    owner: "ceo",
    higherIsBetter: true,
    thresholds: { green: 1, yellow: 0.9 },
    source: "finance.pnl_proxy",
  },
];
